### ISSUE TITLE
Configure to use the JacksonSerializer

### ISSUE THREAD

**Issue by dhermanns** [AxonFramework/AxonBank#10]
Hi!

One simple question: I was just playing around and tried to use Json to serialize everything instead of the default XML.
I tried to add this to AxonConfig-Class:

```
    @Bean
    public Serializer serializer() {
        return new JacksonSerializer();
    }
```

I can see that a JacksonSerializer serializer-Bean is created when running as a docker Container.
But the events in the MySql DB are still encoded as XML. Any hints?

Thx,
Dirk

**Comment by smcvb** [comment]
Hi Dirk,

Are you running Axon with the Spring Boot Axon auto configure?
If so I'd say that the `AxonAutoConfiguration` class shouldn't make a
`XStreamSerializer`, since the annotation on that `@Bean` function is
'ConditionalOnMissingBean of type Serializer'.

If you aren't running it through Spring Boot, then you'd have to set the
JacksonSerializer on the desired location yourself.

I think any specifics on what your config currently looks like could help
to answer your question.

Hope this helps.

Cheers, Steven

**Comment by dhermanns** [comment]
Yes - I'm running with spring boot and saw the Conditional. Wenn adding spring actuator and calling /beans I can see that JacksonSerializer has been instantiated as a bean:

```
{
bean: "serializer",
aliases: [ ],
scope: "singleton",
type: "org.axonframework.serialization.json.JacksonSerializer",
resource: "class path resource [org/axonframework/samples/bank/config/AxonConfig.class]",
dependencies: [ ]
},
```

But nevertheless when looking into the payload e.g. the domain_event_entry table, i see

```
<org.axonframework.samples.bank.api.bankaccount.BankAccountCreatedEvent>
  <id>89d0df66-9d65-463b-8e37-08b4caf8da57</id>
  <overdraftLimit>1234</overdraftLimit>
</org.axonframework.samples.bank.api.bankaccount.BankAccountCreatedEvent>
```

**Comment by smcvb** [comment]
Ah sorry, missed it was about the AxonBank at first, my bad.
What I think is the issue is the axon version. 

By guessing you're using JPA (correct?), I see that the `JpaConfiguration` on creating the `EventStorageEngine` doesn't take the serializer bean into account yet in version 3.0.1. 

Just checked regarding 3.0.2, but the same issue is there as well.

To work around this for now you have to also provide your own `EventStorageEngine` bean and add the `JacksonSerializer` to it. Or you could run on a snapshot of axon for now. Whichever you prefer :)

Hope to have helped!

**Comment by dhermanns** [comment]
Great - that helped. Thanks a lot!

For others: This is my workaround to get Json serialization up and running.
I added this to the AxonConfig Class:

```
    @PersistenceContext
    private EntityManager entityManager;

    @Bean
    public EventStorageEngine eventStorageEngine(DataSource dataSource) throws SQLException {

        EntityManagerProvider entityManagerProvider = new SimpleEntityManagerProvider(entityManager);
        return new JpaEventStorageEngine(serializer(), NoOpEventUpcaster.INSTANCE, dataSource, entityManagerProvider, NoTransactionManager.INSTANCE);
    }
```

**Comment by dhermanns** [comment]
Oh - too soon closed :) . There is one more problem after the first snapshot was taken: The payload in the snapshot_event_entry-Table is missing. 

Maybe this has something to do with Jackson wanting default constructors in the MoneyDepositedEvent.
After one snapshot has been created, I got a:

```
org.axonframework.eventsourcing.IncompatibleAggregateException: Aggregate identifier must be non-null after applying an event. Make sure the aggregate identifier is initialized at the latest when handling the creation event.
	at org.axonframework.eventsourcing.EventSourcedAggregate.publish(EventSourcedAggregate.java:160) ~[axon-core-3.0.2.jar:3.0.2]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[na:1.8.0_73]
	at org.axonframework.eventsourcing.EventSourcedAggregate.lambda$initializeState$1(EventSourcedAggregate.java:212) ~[axon-core-3.0.2.jar:3.0.2]
	at org.axonframework.commandhandling.model.inspection.AnnotatedAggregate.lambda$execute$2(AnnotatedAggregate.java:172) ~[axon-core-3.0.2.jar:3.0.2]
	at org.axonframework.commandhandling.model.AggregateLifecycle.lambda$execute$2(AggregateLifecycle.java:186) ~[axon-core-3.0.2.jar:3.0.2]
	at org.axonframework.commandhandling.model.AggregateLifecycle.executeWithResult(AggregateLifecycle.java:167) ~[axon-core-3.0.2.jar:3.0.2]
	at org.axonframework.commandhandling.model.AggregateLifecycle.execute(AggregateLifecycle.java:185) ~[axon-core-3.0.2.jar:3.0.2]
	at org.axonframework.commandhandling.model.inspection.AnnotatedAggregate.execute(AnnotatedAggregate.java:172) ~[axon-core-3.0.2.jar:3.0.2]
	at org.axonframework.eventsourcing.EventSourcedAggregate.initializeState(EventSourcedAggregate.java:209) ~[axon-core-3.0.2.jar:3.0.2]
	at org.axonframework.eventsourcing.EventSourcingRepository.doLoadWithLock(EventSourcingRepository.java:182) ~[axon-core-3.0.2.jar:3.0.2]
	at org.axonframework.eventsourcing.EventSourcingRepository.doLoadWithLock(EventSourcingRepository.java:44) ~[axon-core-3.0.2.jar:3.0.2]
	at org.axonframework.commandhandling.model.LockingRepository.doLoad(LockingRepository.java:139) ~[axon-core-3.0.2.jar:3.0.2]
	at org.axonframework.commandhandling.model.LockingRepository.doLoad(LockingRepository.java:48) ~[axon-core-3.0.2.jar:3.0.2]
	at org.axonframework.commandhandling.model.AbstractRepository.lambda$load$7(AbstractRepository.java:111) ~[axon-core-3.0.2.jar:3.0.2]
	at java.util.HashMap.computeIfAbsent(HashMap.java:1118) ~[na:1.8.0_73]
	at org.axonframework.commandhandling.model.AbstractRepository.load(AbstractRepository.java:110) ~[axon-core-3.0.2.jar:3.0.2]
	at org.axonframework.commandhandling.model.AbstractRepository.load(AbstractRepository.java:135) ~[axon-core-3.0.2.jar:3.0.2]
	at org.axonframework.samples.bank.command.BankAccountCommandHandler.handle(BankAccountCommandHandler.java:52) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_73]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_73]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_73]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_73]
	at org.axonframework.messaging.annotation.AnnotatedMessageHandlingMember.handle(AnnotatedMessageHandlingMember.java:127) ~[axon-core-3.0.2.jar:3.0.2]
	at org.axonframework.messaging.annotation.WrappedMessageHandlingMember.handle(WrappedMessageHandlingMember.java:61) ~[axon-core-3.0.2.jar:3.0.2]
	at org.axonframework.commandhandling.AnnotationCommandHandlerAdapter.handle(AnnotationCommandHandlerAdapter.java:94) ~[axon-core-3.0.2.jar:3.0.2]
	at org.axonframework.commandhandling.AnnotationCommandHandlerAdapter.handle(AnnotationCommandHandlerAdapter.java:38) ~[axon-core-3.0.2.jar:3.0.2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_73]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_73]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_73]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_73]
	at org.axonframework.spring.config.AbstractAnnotationHandlerBeanPostProcessor$AdapterIntroductionInterceptor.invoke(AbstractAnnotationHandlerBeanPostProcessor.java:252) ~[axon-spring-3.0.2.jar:3.0.2]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:656) ~[spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.axonframework.samples.bank.command.BankAccountCommandHandler$$EnhancerBySpringCGLIB$$e36773eb.handle(<generated>) ~[classes/:na]
	at org.axonframework.messaging.DefaultInterceptorChain.proceed(DefaultInterceptorChain.java:57) ~[axon-core-3.0.2.jar:3.0.2]
	at org.axonframework.messaging.unitofwork.DefaultUnitOfWork.executeWithResult(DefaultUnitOfWork.java:69) ~[axon-core-3.0.2.jar:3.0.2]
	at org.axonframework.commandhandling.SimpleCommandBus.doDispatch(SimpleCommandBus.java:145) [axon-core-3.0.2.jar:3.0.2]
	at org.axonframework.commandhandling.SimpleCommandBus.doDispatch(SimpleCommandBus.java:118) [axon-core-3.0.2.jar:3.0.2]
	at org.axonframework.commandhandling.SimpleCommandBus.dispatch(SimpleCommandBus.java:88) [axon-core-3.0.2.jar:3.0.2]
	at org.axonframework.commandhandling.CommandBus.dispatch(CommandBus.java:45) [axon-core-3.0.2.jar:3.0.2]
	at org.axonframework.samples.bank.web.BankAccountController.deposit(BankAccountController.java:77) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_73]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_73]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_73]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_73]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:180) [spring-messaging-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:112) [spring-messaging-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMatch(AbstractMethodMessageHandler.java:502) [spring-messaging-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.messaging.simp.annotation.support.SimpAnnotationMethodMessageHandler.handleMatch(SimpAnnotationMethodMessageHandler.java:497) [spring-messaging-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.messaging.simp.annotation.support.SimpAnnotationMethodMessageHandler.handleMatch(SimpAnnotationMethodMessageHandler.java:87) [spring-messaging-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMessageInternal(AbstractMethodMessageHandler.java:461) [spring-messaging-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMessage(AbstractMethodMessageHandler.java:399) [spring-messaging-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.run(ExecutorSubscribableChannel.java:135) [spring-messaging-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_73]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_73]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_73]
```

I think this is a follow up error due to the not correctly created snapshot. Any Ideas?

**Comment by dhermanns** [comment]
Oh - my fault. I missed that there aren't any getter/setter for the fields in the BankAccount Aggregate. Therefore Jackson per default doesn't serialize the aggregate id which leads to the error above.

So the correct Jackson Definition has to be:

```
@Bean
public Serializer serializer() {

        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.setVisibility(PropertyAccessor.FIELD, JsonAutoDetect.Visibility.ANY);
        return new JacksonSerializer(objectMapper);
}
```

Of cause you have to take care what private fields are in your Events/Commands/Aggregates because now Jackson will serialize all fields.

Hope this saves someone else some time in setting up json with axon.
