### ISSUE TITLE
Error starting ApplicationContext

### ISSUE THREAD

**Issue by VitaliyKulikov** [AxonFramework/AxonBank#16]
Just cloned repo after build, Application can't start-up
- with command:  mvn -pl web spring-boot:run
```
Caused by: java.lang.IllegalArgumentException: Aggregate BankAccount has not been configured
	at org.axonframework.config.DefaultConfigurer$ConfigurationImpl.repository(DefaultConfigurer.java:332) ~[axon-core-3.0.4.jar:3.0.4]
	at org.axonframework.spring.config.AxonConfiguration.repository(AxonConfiguration.java:92) ~[axon-spring-3.0.4.jar:3.0.4]
	at org.axonframework.samples.bank.config.AxonConfig.bankAccountCommandHandler(AxonConfig.java:42) ~[classes/:na]
	at org.axonframework.samples.bank.config.AxonConfig$$EnhancerBySpringCGLIB$$14b293c5.CGLIB$bankAccountCommandHandler$0(<generated>) ~[classes/:na]
	at org.axonframework.samples.bank.config.AxonConfig$$EnhancerBySpringCGLIB$$14b293c5$$FastClassBySpringCGLIB$$ecb53cf1.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358) ~[spring-context-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.axonframework.samples.bank.config.AxonConfig$$EnhancerBySpringCGLIB$$14b293c5.bankAccountCommandHandler(<generated>) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
```
- with: java -jar web/target/axon-bank-web-0.0.1-SNAPSHOT.jar
```
Caused by: java.lang.NullPointerException: null
	at org.axonframework.spring.config.AxonConfiguration.getComponent(AxonConfiguration.java:97) ~[axon-spring-3.0.4.jar!/:3.0.4]
	at org.axonframework.config.Configuration.getComponent(Configuration.java:114) ~[axon-core-3.0.4.jar!/:3.0.4]
	at org.axonframework.boot.autoconfig.JpaAutoConfiguration.eventStorageEngine(JpaAutoConfiguration.java:57) ~[axon-spring-boot-autoconfigure-3.0.4.jar!/:3.0.4]
	at org.axonframework.boot.autoconfig.JpaAutoConfiguration$$EnhancerBySpringCGLIB$$e7318512.CGLIB$eventStorageEngine$5(<generated>) ~[axon-spring-boot-autoconfigure-3.0.4.jar!/:3.0.4]
	at org.axonframework.boot.autoconfig.JpaAutoConfiguration$$EnhancerBySpringCGLIB$$e7318512$$FastClassBySpringCGLIB$$aa108eca.invoke(<generated>) ~[axon-spring-boot-autoconfigure-3.0.4.jar!/:3.0.4]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.axonframework.boot.autoconfig.JpaAutoConfiguration$$EnhancerBySpringCGLIB$$e7318512.eventStorageEngine(<generated>) ~[axon-spring-boot-autoconfigure-3.0.4.jar!/:3.0.4]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]

```

```
$ java -version
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-0ubuntu1.17.04.1-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
```

**Comment by nutteen** [comment]
I'm using Java version: 1.8.0_151 - vendor: Oracle Corporation, in Ubuntu. I have the same problem.

**Comment by smcvb** [comment]
Hi @VitaliyKulikov and @nutteen, I'd like to extend my apologies for the tremendous radio silence you have experienced here.
Back in the day, AxonIQ's efforts were rather stretched thin and we sadly missed this issue from you.

Now, the reason I'm commenting though is that I'm closing this issue due to inactivity. 
Furthermore, this sample project this being archived, so we're not planning any active development on this anymore.

If you're looking for a sample project from AxonIQ to start playing around with this, I recommend the [GiftCard](https://github.com/AxonIQ/giftcard-demo) or [Hotel](https://github.com/AxonIQ/hotel-demo) applications.
