### ISSUE TITLE
Switch to axon 3.0 final release

### ISSUE THREAD

**Issue by jangalinski** [AxonFramework/AxonBank#4]
I noticed some compile errors when switching to latest, seems like some dependencies and test tools changed from RC to RELEASE.
Would be nice to have the example reflect the final version.

Reproduce: switch version to 3.0 in pom.xml, fix errors

**Comment by jangalinski** [comment]
Update: compiles after I 
* renamed to FixtureExecutionResult expectDispatchedCommands in saga tests and
* added  spring-messaging dependency to "query"

But when running the embedded example, I now get this exception when I trigger a transfer:

```
javax.persistence.TransactionRequiredException: No EntityManager with actual transaction available for current thread - cannot reliably process 'persist' call
        at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:282) ~[spring-orm-4.3.5.RELEASE.jar:4.3.5.RELEASE]
        at com.sun.proxy.$Proxy122.persist(Unknown Source) ~[na:na]
        at org.axonframework.eventhandling.saga.repository.jpa.JpaSagaStore.insertSaga(JpaSagaStore.java:260) ~[axon-core-3.0.jar:3.0]
        at org.axonframework.eventhandling.saga.repository.AnnotatedSagaRepository.storeSaga(AnnotatedSagaRepository.java:217) ~[axon-core-3.0.jar:3.0]
        at org.axonframework.eventhandling.saga.repository.AnnotatedSagaRepository.lambda$doCreateInstance$3(AnnotatedSagaRepository.java:138) ~[axon-core-3.0.jar:3.0]
        at org.axonframework.messaging.unitofwork.MessageProcessingContext.notifyHandlers(MessageProcessingContext.java:68) ~[axon-core-3.0.jar:3.0]
        at org.axonframework.messaging.unitofwork.BatchingUnitOfWork.lambda$notifyHandlers$2(BatchingUnitOfWork.java:131) ~[axon-core-3.0.jar:3.0]

```

see https://github.com/jangalinski/AxonBank/tree/switch_to_30final

**Comment by jvanderkallen** [comment]
Hi. I updated the project to use version 3.0 of Axon Framework.

**Comment by langkcc** [comment]
hi，I use version 3.0.4 of Axon Framework.and occur same exception.are you fixed?how?thank you.
